---
# yamllint disable-line rule:truthy
on: [push]

jobs:
  denverton:
    runs-on: ubuntu-latest
    name: Job builds Denverton kernel modules
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Kernel configure and build
        uses: ./  # Uses this repo action
        id: build
        with:
          artifacts: net/ipv4/netfilter/ipt_REJECT.ko net/ipv4/netfilter/nf_reject_ipv4.ko net/netfilter/xt_comment.ko
          dsm-version: '7.2'
          module-deactivate: CONFIG_NFSD CONFIG_NFS_FS
          module-modularize: CONFIG_IP_NF_TARGET_REJECT CONFIG_NETFILTER_XT_MATCH_COMMENT
          package-arch: 'denverton'
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: denverton-7.2-modules
          path: ${{ github.workspace }}/${{ steps.build.outputs.archive }}
